### ISSUE TITLE
requesting you another app because you add apps quickly whenever I ask you (just kidding)

### ISSUE THREAD

**Issue by SonaliBendre** [TheLastZombie/scoop-bucket#4]
This app has no portable binary. MSI installer. https://imo.im/
I'll learn from your manifest how to write MSI installer

**Comment by SonaliBendre** [comment]
BTW which OS do you use?

**Comment by TheLastZombie** [comment]
I use Ubuntu as my daily driver. I also have a second machine with Windows, which I use to maintain this bucket. I don't always have access to that one though – when you made the other requests I had it next to me, but I'll only be able to work on this one the coming week.

**Comment by TheLastZombie** [comment]
APT is fine, but if I had to pick again, I'd probably go with Nix today.

I do occasionally use it, though I'd prefer something more established for communication, such as Matrix or good old e-mail. What do you want to talk about?

**Comment by SonaliBendre** [comment]
>What do you want to talk about?

nvm, I just said out of curiosity

**Comment by SonaliBendre** [comment]
https://github.com/ScoopInstaller/Extras/pull/8047
